CREATE TABLE IF NOT EXISTS frontend_configs (
  id BIGINT UNSIGNED PRIMARY KEY, config_key VARCHAR(100) NOT NULL,
  config_value_json JSON NOT NULL, config_type VARCHAR(24) NOT NULL,
  description VARCHAR(300) NULL, enabled TINYINT(1) NOT NULL DEFAULT 1,
  is_public TINYINT(1) NOT NULL DEFAULT 0, created_at VARCHAR(40) NOT NULL,
  updated_at VARCHAR(40) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS admin_operation_logs (
  id BIGINT UNSIGNED PRIMARY KEY, admin_id BIGINT UNSIGNED NULL,
  action VARCHAR(80) NOT NULL, target_type VARCHAR(48) NOT NULL,
  target_id BIGINT UNSIGNED NULL, detail TEXT NULL, payload_json JSON NOT NULL,
  created_at VARCHAR(40) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS uploaded_files (
  id BIGINT UNSIGNED PRIMARY KEY, owner_user_id BIGINT UNSIGNED NOT NULL,
  purpose VARCHAR(64) NOT NULL, storage_provider VARCHAR(32) NOT NULL,
  storage_key VARCHAR(512) NOT NULL, public_url VARCHAR(1024) NOT NULL,
  mime_type VARCHAR(80) NOT NULL, size_bytes BIGINT UNSIGNED NOT NULL,
  status VARCHAR(24) NOT NULL, created_at VARCHAR(40) NOT NULL,
  updated_at VARCHAR(40) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
