CREATE UNIQUE INDEX uq_app_users_openid ON app_users (openid);
CREATE UNIQUE INDEX uq_app_users_phone ON app_users (phone);
CREATE UNIQUE INDEX uq_app_users_username ON app_users (account_username);
CREATE UNIQUE INDEX uq_admin_users_username ON admin_users (username);
CREATE UNIQUE INDEX uq_admin_users_phone ON admin_users (phone);
CREATE UNIQUE INDEX uq_admin_login_tickets_ticket ON admin_login_tickets (ticket);
CREATE UNIQUE INDEX uq_token_revocations_hash ON token_revocations (token_hash);
CREATE UNIQUE INDEX uq_parent_profiles_user ON parent_profiles (user_id);
CREATE UNIQUE INDEX uq_teachers_user ON teachers (user_id);
CREATE UNIQUE INDEX uq_teacher_subject ON teacher_subjects (teacher_id, subject, teach_grade);
CREATE UNIQUE INDEX uq_order_no ON tutor_orders (order_no);
CREATE UNIQUE INDEX uq_review_order ON reviews (order_id);
CREATE UNIQUE INDEX uq_complaint_no ON complaints (complaint_no);
CREATE UNIQUE INDEX uq_unlock_target ON unlock_records (buyer_user_id, target_type, target_id);
CREATE UNIQUE INDEX uq_payment_order_no ON payment_orders (order_no);
CREATE UNIQUE INDEX uq_payment_merchant_no ON payment_orders (merchant_order_no);
CREATE UNIQUE INDEX uq_payment_idempotency ON payment_orders (idempotency_key);
CREATE UNIQUE INDEX uq_frontend_config_key ON frontend_configs (config_key);
CREATE UNIQUE INDEX uq_uploaded_storage_key ON uploaded_files (storage_provider, storage_key);

CREATE INDEX idx_users_status ON app_users (account_status, profile_status);
CREATE INDEX idx_teacher_visibility ON teachers (audit_status, order_status, is_recommended);
CREATE INDEX idx_teacher_subject_filter ON teacher_subjects (subject, teach_grade, teacher_id);
CREATE INDEX idx_teacher_certification ON teacher_certifications (teacher_id, audit_status);
CREATE INDEX idx_requirement_filter ON parent_requirements (status, child_grade, subject, district, created_at);
CREATE INDEX idx_order_parent_status ON tutor_orders (parent_user_id, status, created_at);
CREATE INDEX idx_order_teacher_status ON tutor_orders (teacher_id, status, created_at);
CREATE INDEX idx_order_status_log ON order_status_logs (order_id, created_at);
CREATE INDEX idx_review_teacher ON reviews (teacher_id, is_visible, created_at);
CREATE INDEX idx_complaint_status ON complaints (status, created_at);
CREATE INDEX idx_unlock_buyer ON unlock_records (buyer_user_id, buyer_role, created_at);
CREATE INDEX idx_payment_buyer_status ON payment_orders (buyer_user_id, pay_status, created_at);
CREATE INDEX idx_contact_target ON contact_logs (user_id, target_type, target_id);
CREATE INDEX idx_phone_verification ON phone_verifications (phone, expires_at);
CREATE INDEX idx_operation_log ON admin_operation_logs (admin_id, action, created_at);
CREATE INDEX idx_uploaded_owner ON uploaded_files (owner_user_id, purpose, created_at);
